use_frameworks!

platform :ios, '9.0'

target 'AXTransitioningObserver_Example' do
  pod 'AXTransitioningObserver', :path => '../'
  pod 'Masonry'
  target 'AXTransitioningObserver_Tests' do
    inherit! :search_paths

    
  end
end
